---
languages:
  cpp:
    extensions:
      - '*.hxx'
      - '*.cxx'
engines:
  coverage:
    enabled: true
    exclude_paths:
      - tests/**
      - examples/**
  bandit:
    enabled: true
    include_paths:
      - tools/pylib/**
  cppcheck:
    enabled: true
  pylint:
    enable: true
    include_paths:
      - tools/pylib/**
  prospector:
    enable: true
    include_paths:
      - tools/pylib/**
